### PR TITLE
updated section about.html

### PR DESCRIPTION
**Pull request by karthikb351**
Added Karthik Balakrishnan :stuck_out_tongue:

### CODE REVIEW

**Comment by jace** [comment]
Needs to be in alphabetic order by first name.

**Comment by karthikb351** [comment]
Sorry! I'm new here - :beginner:

**Comment by jace** [comment]
Just reorder and we'll merge.

**Comment by karthikb351** [comment]
@rudimk is working on this too it seems. You might to inform him that it has to be reordered :/

**Comment by rudimk** [comment]
On it.

**Pull request merged**
